fix(ci): pull before pushing version bump if necessary (#536)

diff --git a/.github/actions/zimic-bump-version/action.yaml b/.github/actions/zimic-bump-version/action.yaml
--- a/.github/actions/zimic-bump-version/action.yaml
+++ b/.github/actions/zimic-bump-version/action.yaml
@@ -74,7 +74,22 @@ runs:
 
         echo 'Pushing changes...'
 
-        git push -u origin HEAD --no-verify
+        numberOfPushRetries=0
+        maxNumberOfPushRetries=3
+
+        git config pull.rebase true
+
+        until git push -u origin HEAD --no-verify; do
+          if [[ $numberOfPushRetries -gt $maxNumberOfPushRetries ]]; then
+            echo "Push failed after $maxNumberOfPushRetries retries. Aborting."
+            exit 1
+          fi
+
+          numberOfPushRetries=$((numberOfPushRetries + 1))
+
+          echo 'Push rejected. Retrying...'
+          git pull
+        done
 
         echo "value=$bumpedVersion" >> $GITHUB_OUTPUT
         echo "commit-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
